app = "vpn-proxy"
primary_region = "fra"

[build]
dockerfile = "./Dockerfile"

[[services]]
internal_port = 443
protocol = "tcp"

  [[services.ports]]
  port = 443
  handlers = []  # без HTTPS, чтобы не пытался проверять HTTP

  [[services.tcp_checks]]
  interval = "30s"
  timeout = "10s"
