# fly.toml app configuration file generated for vpn-proxy-damp-dream-9053 on 2025-08-04T00:31:23-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vpn-proxy-damp-dream-9053'
primary_region = 'fra'

[build]
  dockerfile = './Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 8443

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
