app = "vpn-proxy"
primary_region = "fra"

[http_service]
  internal_port = 443
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 443

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "5s"
