app = "vpn-proxy"
primary_region = "fra"

[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = []

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
