services:
  - type: web
    name: haproxy-proxy
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    region: frankfurt
    envVars:
      - key: RENDER_SERVICE_NAME
        value: haproxy-proxy
