services:
  - type: web
    name: vpnproxy1
    env: docker
    plan: free
    autoDeploy: true
    rootDir: .
    dockerfilePath: ./Dockerfile
    disk:
      name: cert-disk
      mountPath: /etc/haproxy/certs
      sizeGB: 1
    ports:
      - port: 443
        protocol: tcp
